language: objective-c

env:
  matrix:
    - CMAKE_CXX_COMPILER=g++ CMAKE_C_COMPILER=gcc
      CMAKE_BUILD_TYPE=RELEASE
    - CMAKE_CXX_COMPILER=g++ CMAKE_C_COMPILER=gcc
      CMAKE_BUILD_TYPE=DEBUG

install:
 - brew update > /dev/null
 - brew --config
 - brew --env
 # gcc-4.8
 - wget http://dreal.cs.cmu.edu/required_packages/gcc-4.8-bin.tar.gz
 - sudo tar xfz gcc-4.8-bin.tar.gz -C /
 - sudo chown -R `whoami` /usr/local
 - CPLUS_INCLUDE_PATH=/usr/local/include/c++/4.8.1/:/usr/local/include/c++/4.8.1/x86_64-apple-darwin12.5.0:/usr/local/include/c++/4.8.1/bits/
 - export CPLUS_INCLUDE_PATH
 - LIBRARY_PATH=/usr/local/lib:/usr/local/lib/gcc/x86_64-apple-darwin12.5.0/4.8.1/
 - export LIBRARY_PATH
 - rm gcc-4.8-bin.tar.gz
 # autoconf automake cmake libtool pkg-config
 - brew install autoconf libtool pkg-config
 # ocaml, opam, ocamlfind, ocaml-batteries
# - brew install ocaml
# - brew install opam --without-aspcud
# - yes | opam init
# - eval `opam config env`
# - opam update
# - yes | opam install ocamlfind batteries oasis

before_script:
  - SITE=OSX10.8.5@Travis
  - if [[ $CMAKE_BUILD_TYPE == RELEASE ]]; then
      BUILD_TYPE=Release;
    else
      BUILD_TYPE=Debug;
    fi
  - BUILD_NAME=${TRAVIS_BRANCH}_g++-4.9.0_${BUILD_TYPE}
  - GIT_COMMIT=`git log HEAD~ --oneline -n 1 | cut -d ' ' -f 1`
  - GIT_SUBJECT=`git log HEAD~ --oneline -n 1 | cut -d ' ' -f 2-`
  - GIT_SUBJECT=${GIT_SUBJECT//\"/\\\"}
  - GIT_SUBJECT=${GIT_SUBJECT//,/\,}
  - GIT_SUBJECT=$(echo -e $(printf '%q' "$GIT_SUBJECT"))

script:
  # compile dReal
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=/usr/local/bin/${CMAKE_CXX_COMPILER} -DCMAKE_C_COMPILER=/usr/local/bin/${CMAKE_C_COMPILER} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ../src
  - CONFIG_FILE=DartConfiguration.tcl
  - sed -i "" "s/^Site:.*/Site:$SITE/" $CONFIG_FILE
  - sed -i "" "s/BuildName:.*/BuildName:$BUILD_NAME/" $CONFIG_FILE
  - ctest -D ExperimentalConfigure
  - sed -i "" "s/^Site:.*/Site:$SITE/" $CONFIG_FILE
  - sed -i "" "s/BuildName:.*/BuildName:$BUILD_NAME/" $CONFIG_FILE
  - ctest -D ExperimentalBuild -VV
  - cd ..
  # compile tools
  # - make -C tools

after_script:
  - cd build
  - ctest -D ExperimentalTest --timeout 500 -E ".*delta.*" -VV
  - find Testing -name "*.xml" -exec sed -i "" "s,Generator=\".*\",Generator=\"${GIT_COMMIT}###${GIT_SUBJECT}\"," {} ";"
  - find Testing \( -name "LastTest_*.log" -o -name "LastDynamicAnalysis_*.log" \) -exec sh -c 'TMP=`mktemp /tmp/ctesttmp_XXXX`; ../script/demangle_cpptype.py {} > $TMP; mv -v $TMP {}' ";"
  - ctest -D ExperimentalSubmit
  - cd ..

notifications:
  email:
    recipients:
     - dreal-dev@googlegroups.com
    on_success: always
    on_failure: always
